Restart:
  needs: Copy
  runs-on: ubuntu-latest
  steps:
    - name: Restart Alwaysdata site
      run: |
        response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST --basic --user "${{ secrets.ALWAYSDATA_TOKEN }}:" https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_SITE_ID }}/restart/)
        # Vérifier le code de réponse HTTP
        if [ "$response_code" -eq 204 ]; then
          echo "Relance de votre site réussi"
        elif [ "$response_code" -eq 404 ]; then
          echo "Vous n'avez pas renseigner correctement votre secret ALWAYSDATA_SITE_ID"
          exit 1  # Quitter avec un code d'erreur
        elif [ "$response_code" -eq 401 ]; then
          echo "Vous n'avez pas renseigner correctement votre secret ALWAYSDATA_TOKEN"
          exit 1  # Quitter avec un code d'erreur
        else
          echo "Échec du redémarrage avec le code de réponse : $response_code"
          exit 1  # Quitter avec un code d'erreur
        fi  # <-- Ajout du 'fi' pour fermer la structure conditionnelle
